### ISSUE TITLE
Bouw: Laadscherm

### ISSUE THREAD

**Issue by mosbuma** [Stichting-CROW/fietsberaad-veiligstallen-app#15]

**Comment by mosbuma** [comment]
[] [Tekst] [veiligstallen.nl](http://veiligstallen.nl/)

**Comment by bartwr** [comment]
Dit wordt een PWA (Progressive Web App) splash screen.

**Comment by bartwr** [comment]
Done! 

- https://github.com/Stichting-CROW/fietsberaad-veiligstallen-app/commit/3f446e1321b14f07c4e2baad48c6978029ec1628
- https://github.com/Stichting-CROW/fietsberaad-veiligstallen-app/commit/74fa8976c60f8170814f1b03d1c7ff6a81e124f9
- https://github.com/Stichting-CROW/fietsberaad-veiligstallen-app/commit/4b50aa58973b7f8dec56884d99559396867c061b
- https://github.com/Stichting-CROW/fietsberaad-veiligstallen-app/commit/e8f60bf029aca37db6d0b0843cb4c78afdc4942a
