### ISSUE TITLE
Bouw: Modal Popup Stad

### ISSUE THREAD

**Issue by mosbuma** [Stichting-CROW/fietsberaad-veiligstallen-app#16]

**Comment by mosbuma** [comment]
design - https://xd.adobe.com/view/41747c43-0d49-4dff-ace1-2194006b1a77-1427/screen/ed6e56f7-9e66-4ba7-a1e8-a53b43b8bc7c/
Type modal
- [ ] [Knop] Actie: Zoek een openbare stalling in Stad X
- [ ] [Knop] Actie: Zoek een prive stalling in stad X
- [ ] [Link] Actie: Info over parkeren in stad X
- [ ] [Knop] Actie: Sluit modal scherm

**Comment by bartwr** [comment]
Done
