### ISSUE TITLE
Bouw Card Stallinginformatie

### ISSUE THREAD

**Issue by mosbuma** [Stichting-CROW/fietsberaad-veiligstallen-app#20]
design - https://xd.adobe.com/view/41747c43-0d49-4dff-ace1-2194006b1a77-1427/

- [x] [Tekst]: Naam van de stalling
- [x] [Tekst]: Straatnaam en huisnummer van de stalling
- [x] [Tekst]: Stallingprijs
- [x] [Tekst]: Huidige status open/gesloten
- [x] [Tekst] Afstand tot huidige locatie
- [ ] [Knop]: Actie: Maak route naar stalling (externe applicatie?)

**Comment by bartwr** [comment]
Design is gereed.
