### ISSUE TITLE
Bouw Menu

### ISSUE THREAD

**Issue by mosbuma** [Stichting-CROW/fietsberaad-veiligstallen-app#22]
design: https://xd.adobe.com/view/41747c43-0d49-4dff-ace1-2194006b1a77-1427/screen/f589ab26-2eda-4c8e-a965-0ddf638d0b32/

- [x] - [ ] [Tekstblok met ikoon] Welkom in <Stad>
- [x] [Link] Actie naar de kaartweergave
- [x] [Link] Naar de lijstweergave
- [x] [Link] Koop abonnement]
- [x] [Link] Over Utrecht Fietst!
- [x] [Link] Informatie buurtstallingen
- [x] [Link] Informatie fietstrommels
- [x] [Link] Faq
- [x] [Link] Tips
- [x] [Link] Contact
- [x] [Link] Over veilig stallen
- [ ] [Knop] Registeren
- [ ] [Knop] Inloggen\
- [x] [Link] Disclaimer
- [x] [Link] Privacy
- [x] [Link] Algemene voorwaarden

**Comment by bartwr** [comment]
We laten Registreren en Inloggen achterwege in de mobiele weergave.
