### ISSUE TITLE
Bouw Filterbox

### ISSUE THREAD

**Issue by mosbuma** [Stichting-CROW/fietsberaad-veiligstallen-app#25]
design:https://xd.adobe.com/view/41747c43-0d49-4dff-ace1-2194006b1a77-1427/screen/65889751-6529-477b-af4d-28a7e9d372db/

[Filterbox] Filterbox ingeklapt (transparante achtergrond)
- [x] [Lijst met geselecteerde stallingtypes]
  - [x] [Minibox] 
    - [x] [Ikoon] Stallingtype 
    - [x] [Tekst] Stallingtype
- [ ] Lijst met actieve filteropties
  - [ ] [knop] Actie: verwijder filteroptie
  - [ ] [Tekst] Beschrijving filteroptie

design: https://xd.adobe.com/view/41747c43-0d49-4dff-ace1-2194006b1a77-1427/screen/aa71ef3a-8296-43bb-9b59-a678890574ba/

Filterbox uitgeklapt (witte achtergrond)
- [ ] [Link] Alles wissen
- [ ] [Lijst] Opties Publieke stalling in minibox
  - [ ] [Minibox] <Optie>
    - [ ] [Test] Naam optie
    - [ ] [Actie]: klik = toggle type weergeven / niet weergeven
- [ ] [Lijst] Opties Publieke stalling in minibox
  - [ ] [Minibox] <Optie>
    - [ ] [Test] Naam optie
    - [ ] [Actie]: klik = toggle type weergeven / niet weergeven
- [ ] [Box] 
  - [ ] [Titel] Prijsfilter
  - [ ] [Opties] Per uur / Per dag / Jaarabonnement
  - [ ] Actie: Selecteer 1 van 3
  - [ ] [Slider] Prijs
  - [ ] TODO: Logische range selecteren
- [ ] [Box]
  - [ ] [Titel] Afstand
  - [ ] [Opties] 5 x afstandsoptie
  - [ ] Actie selecteer 1 van N
  - [ ] Actie: Selecteer 1 van 3

**Comment by bartwr** [comment]
Filtermenu is momenteel voldoende af. Het toont de stallingtypes.
